In [200]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

In [56]:
podium_data = pd.read_excel(r'C:\Users\kpopow\Documents\Projects\Podium Project\Podium data.xlsx')

In [59]:
cust_xref = pd.read_excel(r'C:\Users\kpopow\Documents\Projects\Podium Project\Hunter Douglas Orgs and Locations.xlsx', sheet_name='Hunter Douglas Locations')

In [64]:
hd_sales = pd.read_excel(r'C:\Users\kpopow\Documents\Projects\Podium Project\Sales Data\Weekly Sales\Combined Sales File for Podium v2.xlsx', sheet_name='Crosstab')

In [67]:
cust_xref.dtypes

HD Acct #                       float64
podium_org_id                     int64
podium_org_name                  object
podium_location_id                int64
location_name                    object
location_created_date    datetime64[ns]
location_address                 object
location_phone_number            object
dtype: object

In [160]:
cust_xref['HD Acct #'] = cust_xref['HD Acct #'].fillna(0)
cust_xref

,HD Acct #,podium_org_id,podium_org_name,podium_location_id,location_name,location_created_date,location_address,location_phone_number
0,10029272,108174,The Perfect Shade Automated Window Fashions & ...,129667,The Perfect Shade Automated Window Fashions & ...,2020-10-30,"14439 Nw Military Hwy # 628, San Antonio, TX 7...",(210) 495-9995
1,10029714,116035,Budget Blinds of North San Antonio,149362,Budget Blinds of North San Antonio,2021-01-27,"4553 N Loop 1604 W, San Antonio, Texas 78249-1...",+1 210-490-2272
2,10058953,121791,Budget Blinds of South Fayetteville & Fort Smith,157824,Budget Blinds of South Fayetteville & Fort Smith,2021-03-18,"21559 Indian Creek Dr, Garfield, Arkansas 7273...",479) 439-0229
3,10025382,94221,Grand Teton Floor & Window Coverings,111960,Grand Teton Floor & Window Coverings,2020-08-18,"1705 High School Rd Apt 120, Jackson, WY 83001...",+1 307-200-4298
4,10006246,113721,Betz Blinds,145359,"Betz Blinds Inc - 1111 West 41st Street, Sioux...",2020-12-30,"1111 W 41st St, Sioux Falls, SD 57105-6324 US",+1 605-357-0057
...,...,...,...,...,...,...,...,...
226,10038124,117187,Blind Magic Window Coverings,151528,Blind Magic Window Coverings,2021-02-04,"10615 170 Street Northwest, Edmonton, AB T5P 4...",+1 780-900-4589
227,10060721,117027,Shades | Window Fashion Studio,150763,Shades | Window Fashion Studio,2021-02-03,"211 East Washington Street, Greenville, SC 296...",+1 864-297-3737
228,10024205,116750,Fashion Interiors,150455,Fashion Interiors,2021-02-01,"9561 Irvine Center Drive, Irvine, CA 92618 US",+1 949-788-9288
229,10044387,116489,The Curtain,149936,The Curtain,2021-01-29,"503 Broad Ave, Palisades Park, New Jersey 0765...",(201) 302-9111
230,10042570,116321,Rachel Brosky Interiors,149670,Rachel Brosky Interiors,2021-01-28,"104 North Mantle Avenue, Elizabethtown, KY 427...",+1 270-982-0887

In [82]:
cust_xref['HD Acct #'] = cust_xref['HD Acct #'].astype('int64')

In [85]:
hd_sales.dtypes

Acct Key                               object
Sold-To Party                           int64
Podium_Org_ID                         float64
Podium_Location_ID                    float64
Podium_start_date              datetime64[ns]
Podium_start_week                      object
Sales Organization                     object
Reporting Fiscal Week                   int64
Year/Week key                          object
Year                                    int64
Sold-To Party Name                     object
Alliance Level                         object
Exclusive                              object
Sales Office                           object
Attribute                              object
Online/StoreFront                      object
Attribute 3                            object
Has Website                            object
# of Sales Orders per week            float64
# of Opportunities per week           float64
Sales Amount per week                 float64
Sales Qty per week                    float64
dtype: object

In [88]:
hd_sales['Podium_Org_ID'] = hd_sales['Podium_Org_ID'].fillna(0).astype('int64')

In [89]:
hd_sales['Podium_Location_ID'] = hd_sales['Podium_Location_ID'].fillna(0).astype('int64')

In [112]:
hd_sales['Podium_start_week'] = hd_sales['Podium_start_week'].fillna('00')

In [114]:
podium_dealers = hd_sales[hd_sales['Podium_start_week'] != '00']

In [117]:
non_podium = hd_sales[hd_sales['Podium_start_week'] == '00']

In [124]:
sales_totals = podium_dealers.groupby(['Reporting Fiscal Week','Year'])['Sales Amount per week'].sum().reset_index()

In [186]:
podium_dealers.head(5)
len(podium_dealers)

7661

In [135]:
weeks_convert = pd.read_excel(r'C:\Users\kpopow\Documents\Projects\Podium Project\Week file.xlsx',sheet_name='All weeks')
weeks_convert.head(5)

  Year/Week key   numberÂ   From Date    To Date Quarter
0        1/2019         1 2018-12-30 2019-01-05      Q1
1        2/2019         2 2019-01-06 2019-01-12      Q1
2        3/2019         3 2019-01-13 2019-01-19      Q1
3        4/2019         4 2019-01-20 2019-01-26      Q1
4        5/2019         5 2019-01-27 2019-02-02      Q1

In [136]:
hd_sales_rev = hd_sales.merge(weeks_convert, how='left', on='Year/Week key')

In [265]:
hd_sales_rev.head(5)

,Acct Key,HD Acct #,Podium_Org_ID,Podium_Location_ID,Podium_start_date,Podium_start_week,Sales Organization,Reporting Fiscal Week,Year/Week key,Year,...,location_phone_number,Org,Account Name,Podium Dealer,Exclusive Program,Type,Account Record Type,Sales_Region_Cd,Sales Region,Sales Sub Region
0,10000006/11/2020,10000006,0,0,NaT,00,HD Fabrication,11,11/2020,2020,...,NaN,1000.0,Hermsen?s Hardware Inc,N,-None-,Dealer,Fabrication,NP,Northern Plains,NP1
1,10000006/11/2021,10000006,0,0,NaT,00,HD Fabrication,11,11/2021,2021,...,NaN,1000.0,Hermsen?s Hardware Inc,N,-None-,Dealer,Fabrication,NP,Northern Plains,NP1
2,10000006/12/2020,10000006,0,0,NaT,00,HD Fabrication,12,12/2020,2020,...,NaN,1000.0,Hermsen?s Hardware Inc,N,-None-,Dealer,Fabrication,NP,Northern Plains,NP1
3,10000006/12/2021,10000006,0,0,NaT,00,HD Fabrication,12,12/2021,2021,...,NaN,1000.0,Hermsen?s Hardware Inc,N,-None-,Dealer,Fabrication,NP,Northern Plains,NP1
4,10000006/13/2021,10000006,0,0,NaT,00,HD Fabrication,13,13/2021,2021,...,NaN,1000.0,Hermsen?s Hardware Inc,N,-None-,Dealer,Fabrication,NP,Northern Plains,NP1
5,10000006/2/2020,10000006,0,0,NaT,00,HD Fabrication,2,2/2020,2020,...,NaN,1000.0,Hermsen?s Hardware Inc,N,-None-,Dealer,Fabrication,NP,Northern Plains,NP1
6,10000006/3/2020,10000006,0,0,NaT,00,HD Fabrication,3,3/2020,2020,...,NaN,1000.0,Hermsen?s Hardware Inc,N,-None-,Dealer,Fabrication,NP,Northern Plains,NP1
7,10000006/3/2021,10000006,0,0,NaT,00,HD Fabrication,3,3/2021,2021,...,NaN,1000.0,Hermsen?s Hardware Inc,N,-None-,Dealer,Fabrication,NP,Northern Plains,NP1
8,10000006/4/2020,10000006,0,0,NaT,00,HD Fabrication,4,4/2020,2020,...,NaN,1000.0,Hermsen?s Hardware Inc,N,-None-,Dealer,Fabrication,NP,Northern Plains,NP1
9,10000006/42/2020,10000006,0,0,NaT,00,HD Fabrication,42,42/2020,2020,...,NaN,1000.0,Hermsen?s Hardware Inc,N,-None-,Dealer,Fabrication,NP,Northern Plains,NP1
10,10000006/43/2020,10000006,0,0,NaT,00,HD Fabrication,43,43/2020,2020,...,NaN,1000.0,Hermsen?s Hardware Inc,N,-None-,Dealer,Fabrication,NP,Northern Plains,NP1
11,10000006/44/2020,10000006,0,0,NaT,00,HD Fabrication,44,44/2020,2020,...,NaN,1000.0,Hermsen?s Hardware Inc,N,-None-,Dealer,Fabrication,NP,Northern Plains,NP1
12,10000006/45/2019,10000006,0,0,NaT,00,HD Fabrication,45,45/2019,2019,...,NaN,1000.0,Hermsen?s Hardware Inc,N,-None-,Dealer,Fabrication,NP,Northern Plains,NP1
13,10000006/46/2019,10000006,0,0,NaT,00,HD Fabrication,46,46/2019,2019,...,NaN,1000.0,Hermsen?s Hardware Inc,N,-None-,Dealer,Fabrication,NP,Northern Plains,NP1
14,10000006/47/2019,10000006,0,0,NaT,00,HD Fabrication,47,47/2019,2019,...,NaN,1000.0,Hermsen?s Hardware Inc,N,-None-,Dealer,Fabrication,NP,Northern Plains,NP1
15,10000006/49/2019,10000006,0,0,NaT,00,HD Fabrication,49,49/2019,2019,...,NaN,1000.0,Hermsen?s Hardware Inc,N,-None-,Dealer,Fabrication,NP,Northern Plains,NP1
16,10000006/49/2020,10000006,0,0,NaT,00,HD Fabrication,49,49/2020,2020,...,NaN,1000.0,Hermsen?s Hardware Inc,N,-None-,Dealer,Fabrication,NP,Northern Plains,NP1
17,10000006/5/2021,10000006,0,0,NaT,00,HD Fabrication,5,5/2021,2021,...,NaN,1000.0,Hermsen?s Hardware Inc,N,-None-,Dealer,Fabrication,NP,Northern Plains,NP1
18,10000006/51/2019,10000006,0,0,NaT,00,HD Fabrication,51,51/2019,2019,...,NaN,1000.0,Hermsen?s Hardware Inc,N,-None-,Dealer,Fabrication,NP,Northern Plains,NP1
19,10000006/51/2020,10000006,0,0,NaT,00,HD Fabrication,51,51/2020,2020,...,NaN,1000.0,Hermsen?s Hardware Inc,N,-None-,Dealer,Fabrication,NP,Northern Plains,NP1

In [143]:
pod_sales = hd_sales_rev[hd_sales_rev['Podium_start_week'] != '00']

In [144]:
pod_sales.head(5)

,Acct Key,Sold-To Party,Podium_Org_ID,Podium_Location_ID,Podium_start_date,Podium_start_week,Sales Organization,Reporting Fiscal Week,Year/Week key,Year,...,Attribute 3,Has Website,# of Sales Orders per week,# of Opportunities per week,Sales Amount per week,Sales Qty per week,number,From Date,To Date,Quarter
1243,10006135/10/2020,10006135,107797,128939,2020-10-28,44/2020,HD Fabrication,10,10/2020,2020,...,Retail Fabricator,X,27.0,NaN,11615.04,41.0,10,2020-03-01,2020-03-07,Q1
1244,10006135/10/2021,10006135,107797,128939,2020-10-28,44/2020,HD Fabrication,10,10/2021,2021,...,Retail Fabricator,X,27.0,NaN,14560.29,40.0,10,2021-03-07,2021-03-13,Q1
1245,10006135/11/2020,10006135,107797,128939,2020-10-28,44/2020,HD Fabrication,11,11/2020,2020,...,Retail Fabricator,X,26.0,NaN,1628.52,8.0,11,2020-03-08,2020-03-14,Q1
1246,10006135/11/2021,10006135,107797,128939,2020-10-28,44/2020,HD Fabrication,11,11/2021,2021,...,Retail Fabricator,X,26.0,NaN,6298.53,41.0,11,2021-03-14,2021-03-20,Q1
1247,10006135/12/2020,10006135,107797,128939,2020-10-28,44/2020,HD Fabrication,12,12/2020,2020,...,Retail Fabricator,X,31.0,NaN,19313.43,61.0,12,2020-03-15,2020-03-21,Q1

In [148]:
pod_sales_totals = pod_sales.groupby(['Quarter','Year'])['Sales Amount per week'].sum().reset_index()

In [149]:
pod_sales_totals

  Quarter  Year  Sales Amount per week
0      Q1  2020            13311179.49
1      Q1  2021            18944155.87
2      Q2  2021              822708.64
3      Q3  2020              685224.18
4      Q4  2019             9626127.20
5      Q4  2020            17227224.14

In [152]:
non_pod_sales = hd_sales_rev[hd_sales_rev['Podium_start_week'] == '00']
non_pod_sales

,Acct Key,Sold-To Party,Podium_Org_ID,Podium_Location_ID,Podium_start_date,Podium_start_week,Sales Organization,Reporting Fiscal Week,Year/Week key,Year,...,Attribute 3,Has Website,# of Sales Orders per week,# of Opportunities per week,Sales Amount per week,Sales Qty per week,number,From Date,To Date,Quarter
0,10000006/11/2020,10000006,0,0,NaT,00,HD Fabrication,11,11/2020,2020,...,Store Front,NaN,3.0,NaN,96.79,1.0,11,2020-03-08,2020-03-14,Q1
1,10000006/11/2021,10000006,0,0,NaT,00,HD Fabrication,11,11/2021,2021,...,Store Front,NaN,3.0,NaN,3369.73,11.0,11,2021-03-14,2021-03-20,Q1
2,10000006/12/2020,10000006,0,0,NaT,00,HD Fabrication,12,12/2020,2020,...,Store Front,NaN,2.0,NaN,262.99,3.0,12,2020-03-15,2020-03-21,Q1
3,10000006/12/2021,10000006,0,0,NaT,00,HD Fabrication,12,12/2021,2021,...,Store Front,NaN,2.0,NaN,846.44,5.0,12,2021-03-21,2021-03-27,Q1
4,10000006/13/2021,10000006,0,0,NaT,00,HD Fabrication,13,13/2021,2021,...,Store Front,NaN,2.0,NaN,2458.18,8.0,13,2021-03-28,2021-04-03,Q1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178080,10177102/51/2019,10177102,0,0,NaT,00,HD Fabrication,51,51/2019,2019,...,Shop At Home,NaN,1.0,NaN,0.00,10.0,51,2019-12-15,2019-12-21,Q4
178081,10177102/51/2020,10177102,0,0,NaT,00,HD Fabrication,51,51/2020,2020,...,Shop At Home,NaN,1.0,NaN,1636.29,4.0,51,2020-12-13,2020-12-19,Q4
178082,10177102/52/2020,10177102,0,0,NaT,00,HD Fabrication,52,52/2020,2020,...,Shop At Home,NaN,1.0,NaN,1562.50,3.0,52,2020-12-20,2020-12-26,Q4
178083,10177102/8/2020,10177102,0,0,NaT,00,HD Fabrication,8,8/2020,2020,...,Shop At Home,NaN,2.0,NaN,1282.82,5.0,8,2020-02-16,2020-02-22,Q1
178084,10177102/9/2020,10177102,0,0,NaT,00,HD Fabrication,9,9/2020,2020,...,Shop At Home,NaN,1.0,NaN,368.58,2.0,9,2020-02-23,2020-02-29,Q1

In [172]:
non_pod_sales_totals = non_pod_sales.groupby(['Quarter','Year'])['Sales Amount per week'].sum().reset_index()
non_pod_sales_totals

  Quarter  Year  Sales Amount per week
0      Q1  2020           1.253616e+08
1      Q1  2021           1.651100e+08
2      Q2  2021           7.701647e+06
3      Q3  2020           5.887719e+06
4      Q4  2019           9.361179e+07
5      Q4  2020           1.573249e+08

In [161]:
hd_sales_rev.rename(columns={'Sold-To Party': 'HD Acct #'}, inplace=True)

In [166]:
sf_file = pd.read_excel(r'C:\Users\kpopow\Documents\Projects\Podium Project\Sales Data\SF customer data.xlsx', sheet_name='SF acct data')

In [167]:
hd_sales_rev = hd_sales_rev.merge(sf_file, how='left', on='HD Acct #')

In [168]:
hd_sales_rev.head(5)

,Acct Key,HD Acct #,Podium_Org_ID,Podium_Location_ID,Podium_start_date,Podium_start_week,Sales Organization,Reporting Fiscal Week,Year/Week key,Year,...,location_phone_number,Org,Account Name,Podium Dealer,Exclusive Program,Type,Account Record Type,Sales_Region_Cd,Sales Region,Sales Sub Region
0,10000006/11/2020,10000006,0,0,NaT,00,HD Fabrication,11,11/2020,2020,...,NaN,1000.0,Hermsen?s Hardware Inc,N,-None-,Dealer,Fabrication,NP,Northern Plains,NP1
1,10000006/11/2021,10000006,0,0,NaT,00,HD Fabrication,11,11/2021,2021,...,NaN,1000.0,Hermsen?s Hardware Inc,N,-None-,Dealer,Fabrication,NP,Northern Plains,NP1
2,10000006/12/2020,10000006,0,0,NaT,00,HD Fabrication,12,12/2020,2020,...,NaN,1000.0,Hermsen?s Hardware Inc,N,-None-,Dealer,Fabrication,NP,Northern Plains,NP1
3,10000006/12/2021,10000006,0,0,NaT,00,HD Fabrication,12,12/2021,2021,...,NaN,1000.0,Hermsen?s Hardware Inc,N,-None-,Dealer,Fabrication,NP,Northern Plains,NP1
4,10000006/13/2021,10000006,0,0,NaT,00,HD Fabrication,13,13/2021,2021,...,NaN,1000.0,Hermsen?s Hardware Inc,N,-None-,Dealer,Fabrication,NP,Northern Plains,NP1

In [175]:
sales_compare = hd_sales_rev.groupby(['Quarter', 'Year','Podium Dealer'])['Sales Amount per week'].mean().reset_index()

In [176]:
sales_compare

   Quarter  Year Podium Dealer  Sales Amount per week
0       Q1  2020             N            2682.154650
1       Q1  2020             Y            6406.974312
2       Q1  2021             N            3879.990750
3       Q1  2021             Y           10048.796269
4       Q2  2021             N            2965.862370
5       Q2  2021             Y            5932.129308
6       Q3  2020             N            2704.016962
7       Q3  2020             Y            5493.817042
8       Q4  2019             N            3024.427684
9       Q4  2019             Y            7280.503654
10      Q4  2020             N            3600.418210
11      Q4  2020             Y            8730.998027

In [183]:
region_sales_compare = hd_sales_rev.groupby(['Podium Dealer','Year', 'Quarter'])['Sales Amount per week'].mean().reset_index()
region_sales_compare

   Podium Dealer  Year Quarter  Sales Amount per week
0              N  2019      Q4            3024.427684
1              N  2020      Q1            2682.154650
2              N  2020      Q3            2704.016962
3              N  2020      Q4            3600.418210
4              N  2021      Q1            3879.990750
5              N  2021      Q2            2965.862370
6              Y  2019      Q4            7280.503654
7              Y  2020      Q1            6406.974312
8              Y  2020      Q3            5493.817042
9              Y  2020      Q4            8730.998027
10             Y  2021      Q1           10048.796269
11             Y  2021      Q2            5932.129308

In [189]:
podium_accts = hd_sales_rev[hd_sales_rev['Podium Dealer'] == 'Y']
podium_accts.head(5)

,Acct Key,HD Acct #,Podium_Org_ID,Podium_Location_ID,Podium_start_date,Podium_start_week,Sales Organization,Reporting Fiscal Week,Year/Week key,Year,...,location_phone_number,Org,Account Name,Podium Dealer,Exclusive Program,Type,Account Record Type,Sales_Region_Cd,Sales Region,Sales Sub Region
1337,10006135/10/2020,10006135,107797,128939,2020-10-28,44/2020,HD Fabrication,10,10/2020,2020,...,+1 630-871-2907,1000.0,Hang And Shine,Y,Centurion,Dealer,Fabrication,NP,Northern Plains,NP2
1338,10006135/10/2021,10006135,107797,128939,2020-10-28,44/2020,HD Fabrication,10,10/2021,2021,...,+1 630-871-2907,1000.0,Hang And Shine,Y,Centurion,Dealer,Fabrication,NP,Northern Plains,NP2
1339,10006135/11/2020,10006135,107797,128939,2020-10-28,44/2020,HD Fabrication,11,11/2020,2020,...,+1 630-871-2907,1000.0,Hang And Shine,Y,Centurion,Dealer,Fabrication,NP,Northern Plains,NP2
1340,10006135/11/2021,10006135,107797,128939,2020-10-28,44/2020,HD Fabrication,11,11/2021,2021,...,+1 630-871-2907,1000.0,Hang And Shine,Y,Centurion,Dealer,Fabrication,NP,Northern Plains,NP2
1341,10006135/12/2020,10006135,107797,128939,2020-10-28,44/2020,HD Fabrication,12,12/2020,2020,...,+1 630-871-2907,1000.0,Hang And Shine,Y,Centurion,Dealer,Fabrication,NP,Northern Plains,NP2

In [187]:
podium_accts['HD Acct #'].nunique()

198

In [205]:
acct_sales = podium_accts.groupby(['Account Name', 'Year/Week key'])['Sales Amount per week'].sum().reset_index()
acct_sales_pivot = acct_sales.pivot(columns='Year/Week key', index='Account Name', values='Sales Amount per week').reset_index()
acct_sales_pivot

Year/Week key,Account Name,1/2020,10/2020,10/2021,11/2020,11/2021,12/2020,12/2021,13/2020,13/2021,...,53/2019,53/2020,6/2020,6/2021,7/2020,7/2021,8/2020,8/2021,9/2020,9/2021
0,7.0 Blinds,NaN,0.00,NaN,NaN,NaN,NaN,NaN,0.00,NaN,...,NaN,NaN,NaN,4432.44,1351.72,1529.50,4010.48,1155.06,NaN,NaN
1,Accent Window Fashions,133.87,5358.87,3527.92,646.35,11886.88,1530.28,1602.08,NaN,5937.22,...,NaN,1850.67,1772.80,5285.32,NaN,NaN,1822.66,1428.64,NaN,1874.42
2,Adkin's Drapery Shop,NaN,13042.18,4193.80,1749.98,5207.65,5549.65,80.26,3659.17,667.84,...,NaN,654.30,9423.61,6373.55,7751.04,NaN,5177.00,3736.95,121.01,9573.35
3,Affordable Blinds,NaN,NaN,974.40,1543.37,4414.62,1270.50,NaN,NaN,1107.12,...,NaN,NaN,NaN,NaN,NaN,5237.82,NaN,2935.80,109.37,NaN
4,Affordable Blinds & Shutters Inc,8731.48,10979.62,38579.88,12064.28,22697.03,16157.18,59898.49,15302.98,20111.90,...,0.00,17736.94,21784.05,42038.69,1874.06,32757.53,7313.64,21605.95,26182.97,23241.32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188,Window-ology,NaN,6046.64,12531.60,5198.49,4866.26,5558.89,13332.08,3371.18,28375.36,...,NaN,2447.58,5067.53,10653.79,11022.63,41449.14,13281.42,964.85,5288.76,16805.13
189,Windows & Beyond Inc,NaN,0.00,738.41,139.85,NaN,28.79,NaN,139.12,5647.08,...,NaN,698.53,5227.42,1779.54,884.00,NaN,37.80,1176.63,8109.79,434.61
190,Windows Floors & Decor LLC,NaN,0.00,1957.71,NaN,854.88,3666.70,3670.77,NaN,1163.17,...,NaN,NaN,3929.52,2777.28,5296.55,4278.76,NaN,4941.15,NaN,2656.94
191,Woodbury Blinds LLC,NaN,506.00,NaN,NaN,2539.05,0.00,1963.57,NaN,8786.90,...,NaN,NaN,7372.52,869.04,97.04,2173.86,1286.27,NaN,583.57,397.41
192,Z Blinds Company Inc,4381.33,20964.03,11752.48,13599.59,9151.90,20940.50,15624.36,1082.24,8423.59,...,1281.85,20108.12,19195.60,32822.17,21787.39,14051.65,7813.92,6390.27,9276.00,18967.00

In [209]:
podium_may2020_start = hd_sales_rev[(hd_sales_rev['Podium_start_date'] >= '2020-05-01') & (hd_sales_rev['Podium_start_date'] <= '2020-05-31')]

In [211]:
podium_may2020_start['HD Acct #'].nunique()

3

In [214]:
podium_counts = podium_accts.groupby('Podium_start_week')['HD Acct #'].nunique().reset_index()

In [283]:
aug_pod_dealers = hd_sales_rev[(hd_sales_rev['Podium_start_date'] >= '2020-08-01') & (hd_sales_rev['Podium_start_date'] <= '2020-08-31') | (hd_sales_rev['Podium_start_week'] == '00') & (hd_sales_rev['Exclusive Program'] == 'Centurion') & (hd_sales_rev['Sales Amount per week'] != 0.00)]
aug_pod_dealers['Sales Amount per week']

26         3419.91
27         1591.86
28         2208.13
30          423.76
31          332.28
            ...
180960     3846.24
180961       88.20
180962     3762.58
180964     1889.21
180965    11794.58
Name: Sales Amount per week, Length: 58748, dtype: float64

In [294]:
aug_compare = aug_pod_dealers.groupby(['Account Name','Year', 'Quarter',])['Sales Amount per week'].mean().reset_index()

In [295]:
aug_compare

          Account Name  Year Quarter  Sales Amount per week
0      27 Diamonds Inc  2019      Q4            6355.490000
1      27 Diamonds Inc  2020      Q1            5595.904444
2      27 Diamonds Inc  2020      Q3            1623.410000
3      27 Diamonds Inc  2020      Q4            8217.402000
4      27 Diamonds Inc  2021      Q1            2644.586667
...                ...   ...     ...                    ...
11498  Zubek Interiors  2019      Q4            3789.890000
11499  Zubek Interiors  2020      Q1            3192.360000
11500  Zubek Interiors  2020      Q3            3120.960000
11501  Zubek Interiors  2020      Q4            3078.877143
11502  Zubek Interiors  2021      Q1            2979.988000

[11503 rows x 4 columns]

In [308]:
hd_sales_rev = hd_sales_rev.sort_values(by=['Account Name', 'From Date'])
hd_sales_rev['pct_change'] = hd_sales_rev.groupby(['Account Name'])['Sales Amount per week'].pct_change()